server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/loans
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always